/*
 * This class is responsible for handling and setting up the gaphical user interfaces
 * as well as registering all of the java controls and their event handlers\
 * this class also makes use of registering classess into the service locator for
 * classess that store internal references to gui swing controls.
 */
package gui;


import java.awt.CardLayout;
import java.util.InputMismatchException;
import javax.swing.JToggleButton;
import uberstockapp.AdminPanel;
import uberstockapp.CategoryViewController;
import uberstockapp.CheckoutCartController;
import uberstockapp.Login;
import uberstockapp.ProductPreviewController;
import uberstockapp.ServiceLocator;
import uberstockapp.ShoppingCart;

/**
 *
 * @author Kyle and Tri
 */
public class UberStockGuiFrame extends javax.swing.JFrame {
    
   
    
    CardLayout cardLayout = null;
    ServiceLocator serviceLocator = ServiceLocator.getServiceLocatorInstance();
    /**
     * Creates new form UberStockGuiFrame
     */
    public UberStockGuiFrame() {
        initComponents();
        AdminPanelBtn.setVisible(false);
        cardLayout = (CardLayout)contentView.getLayout();
        
        serviceLocator.registerService("ProductPreviewController", new ProductPreviewController(ItemPreviewImage, itemNameLbl, itemPriceLbl, currentStockLbl, cartQuantityToAddField));
        serviceLocator.registerService("CategoryViewController", new CategoryViewController(categoryControlPanel, productBtnGrid));
        serviceLocator.registerService("CheckoutCartController", new CheckoutCartController(checkOutCartPanel, checkoutCartList, toggleMemberJoinBtn,joinMembershipPanel, firstname, middleinitial, lastname,email));
        
        CategoryViewController categoryViewController = (CategoryViewController)serviceLocator.getService("CategoryViewController");
        categoryViewController.buildCategoryView();
        repaint();
        
        contentView.add(loginPanel, "1");
        contentView.add(storePanel, "2");
        contentView.add(registerPanel, "3");
        contentView.add(checkoutPanel, "4");
        contentView.add(AdminPanel,"5");

        incorrectLoginLabel.setVisible(false);

       
        //Dimension screenSize = getToolkit().getScreenSize();
        //add(contentView);
        cardLayout.show(contentView, "1");
        //pack();
        
        //setResizable(false);
        //setSize(screenSize.width,screenSize.height);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentView = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        passwordLbl = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        usernameLbl = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        incorrectLoginLabel = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        registerFormRegisterBtn = new javax.swing.JButton();
        registerFormCancelBtn = new javax.swing.JButton();
        registerFormUsernameField = new javax.swing.JTextField();
        registerUsernameLbl = new javax.swing.JLabel();
        registerPasswordLbl = new javax.swing.JLabel();
        registerConfirmLbl = new javax.swing.JLabel();
        registerSecondConfirmPassword = new javax.swing.JPasswordField();
        registerConfirmPassword = new javax.swing.JPasswordField();
        storePanel = new javax.swing.JPanel();
        productScrollPanel = new javax.swing.JScrollPane();
        productBtnGrid = new javax.swing.JPanel();
        cartScrollPanel = new javax.swing.JScrollPane();
        cartListPanel = new javax.swing.JPanel();
        uberStockNameLbl = new javax.swing.JLabel();
        paintPanel = new javax.swing.JPanel();
        UserNameLbl = new javax.swing.JLabel();
        storeBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        AdminPanelBtn = new javax.swing.JButton();
        previewItemPanel = new javax.swing.JPanel();
        currentStockLbl = new javax.swing.JLabel();
        cartQuantityToAddField = new javax.swing.JTextField();
        currentStockText = new javax.swing.JLabel();
        quantityToAddText = new javax.swing.JLabel();
        ItemPreviewImage = new javax.swing.JLabel();
        itemPriceText = new javax.swing.JLabel();
        addToCartBtn = new javax.swing.JButton();
        cancelAddToCartBtn = new javax.swing.JButton();
        itemPriceLbl = new javax.swing.JLabel();
        itemNameLbl = new javax.swing.JLabel();
        shoppingCartPaintPanel = new javax.swing.JPanel();
        shoppingCartLbl = new javax.swing.JLabel();
        cartTextLbl = new javax.swing.JLabel();
        cartControlPanel = new javax.swing.JPanel();
        checkOutCartBtn = new javax.swing.JButton();
        clearCartBtn = new javax.swing.JButton();
        categoryControlPanel = new javax.swing.JPanel();
        checkoutPanel = new javax.swing.JPanel();
        checkOutCartPanel = new javax.swing.JScrollPane();
        checkoutCartList = new javax.swing.JPanel();
        papaylPanel = new javax.swing.JPanel();
        firstname = new javax.swing.JTextField();
        middleinitial = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        confirmOrderControlPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        joinMembershipPanel = new javax.swing.JPanel();
        toggleMemberJoinBtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        userIDSearchField = new javax.swing.JTextField();
        searchUserHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserHistoryTable = new javax.swing.JTable();
        goBackToStoreBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UberStock");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("uberStockFrame"); // NOI18N
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        contentView.setPreferredSize(new java.awt.Dimension(0, 0));
        contentView.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(252, 252, 252));
        loginPanel.setLayout(new java.awt.GridBagLayout());

        loginBtn.setBackground(new java.awt.Color(206, 209, 213));
        loginBtn.setText("Login");
        loginBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        loginBtn.setMargin(new java.awt.Insets(4, 14, 4, 14));
        loginBtn.setMinimumSize(new java.awt.Dimension(78, 32));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 9, 0, 10);
        loginPanel.add(loginBtn, gridBagConstraints);

        registerBtn.setBackground(new java.awt.Color(206, 209, 213));
        registerBtn.setText("Register");
        registerBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 8);
        loginPanel.add(registerBtn, gridBagConstraints);

        passwordLbl.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        loginPanel.add(passwordLbl, gridBagConstraints);

        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        loginPanel.add(PasswordField, gridBagConstraints);

        usernameLbl.setText("User Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        loginPanel.add(usernameLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        loginPanel.add(UserNameField, gridBagConstraints);

        incorrectLoginLabel.setForeground(new java.awt.Color(255, 0, 0));
        incorrectLoginLabel.setText("Incorrect Username or Password");
        loginPanel.add(incorrectLoginLabel, new java.awt.GridBagConstraints());

        contentView.add(loginPanel, "card2");

        registerPanel.setBackground(new java.awt.Color(252, 252, 252));
        registerPanel.setLayout(new java.awt.GridBagLayout());

        registerFormRegisterBtn.setBackground(new java.awt.Color(206, 209, 213));
        registerFormRegisterBtn.setText("Register");
        registerFormRegisterBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        registerFormRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFormRegisterBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        registerPanel.add(registerFormRegisterBtn, gridBagConstraints);

        registerFormCancelBtn.setBackground(new java.awt.Color(206, 209, 213));
        registerFormCancelBtn.setText("Cancel");
        registerFormCancelBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        registerFormCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFormCancelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 10);
        registerPanel.add(registerFormCancelBtn, gridBagConstraints);

        registerFormUsernameField.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        registerPanel.add(registerFormUsernameField, gridBagConstraints);

        registerUsernameLbl.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 47, 0, 0);
        registerPanel.add(registerUsernameLbl, gridBagConstraints);

        registerPasswordLbl.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 48, 0, 0);
        registerPanel.add(registerPasswordLbl, gridBagConstraints);

        registerConfirmLbl.setText("Confirm Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        registerPanel.add(registerConfirmLbl, gridBagConstraints);

        registerSecondConfirmPassword.setMinimumSize(new java.awt.Dimension(14, 24));
        registerSecondConfirmPassword.setPreferredSize(new java.awt.Dimension(14, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        registerPanel.add(registerSecondConfirmPassword, gridBagConstraints);

        registerConfirmPassword.setMinimumSize(new java.awt.Dimension(14, 24));
        registerConfirmPassword.setPreferredSize(new java.awt.Dimension(14, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        registerPanel.add(registerConfirmPassword, gridBagConstraints);

        contentView.add(registerPanel, "card4");

        storePanel.setBackground(new java.awt.Color(249, 250, 251));
        storePanel.setMinimumSize(new java.awt.Dimension(800, 800));
        storePanel.setLayout(new java.awt.GridBagLayout());

        productScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        productScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        productScrollPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        productScrollPanel.setPreferredSize(new java.awt.Dimension(800, 500));

        productBtnGrid.setMinimumSize(new java.awt.Dimension(400, 400));
        productBtnGrid.setLayout(new java.awt.GridBagLayout());
        productScrollPanel.setViewportView(productBtnGrid);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        storePanel.add(productScrollPanel, gridBagConstraints);

        cartScrollPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        cartScrollPanel.setPreferredSize(new java.awt.Dimension(300, 300));

        cartListPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 2));
        cartScrollPanel.setViewportView(cartListPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 17, 0, 20);
        storePanel.add(cartScrollPanel, gridBagConstraints);

        uberStockNameLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        uberStockNameLbl.setForeground(new java.awt.Color(199, 32, 44));
        uberStockNameLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/uberstockLogo.png"))); // NOI18N
        uberStockNameLbl.setText("UberStock");
        uberStockNameLbl.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        storePanel.add(uberStockNameLbl, gridBagConstraints);

        paintPanel.setBackground(new java.awt.Color(206, 209, 213));
        paintPanel.setMinimumSize(new java.awt.Dimension(550, 60));
        paintPanel.setName(""); // NOI18N
        paintPanel.setPreferredSize(new java.awt.Dimension(400, 60));
        paintPanel.setLayout(new java.awt.GridBagLayout());

        UserNameLbl.setText("Welcome Kyle Klersy");
        UserNameLbl.setPreferredSize(new java.awt.Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        paintPanel.add(UserNameLbl, gridBagConstraints);

        storeBtn.setText("Logout");
        storeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBtnActionPerformed(evt);
            }
        });
        paintPanel.add(storeBtn, new java.awt.GridBagConstraints());

        jButton3.setText("Profile");
        paintPanel.add(jButton3, new java.awt.GridBagConstraints());

        AdminPanelBtn.setText("Admin Panel");
        AdminPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPanelBtnActionPerformed(evt);
            }
        });
        paintPanel.add(AdminPanelBtn, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        storePanel.add(paintPanel, gridBagConstraints);

        previewItemPanel.setMinimumSize(new java.awt.Dimension(350, 350));
        previewItemPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        previewItemPanel.add(currentStockLbl, gridBagConstraints);

        cartQuantityToAddField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cartQuantityToAddField.setMinimumSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        previewItemPanel.add(cartQuantityToAddField, gridBagConstraints);

        currentStockText.setText("Current Stock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        previewItemPanel.add(currentStockText, gridBagConstraints);

        quantityToAddText.setText("Quantity to Add");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        previewItemPanel.add(quantityToAddText, gridBagConstraints);

        ItemPreviewImage.setMaximumSize(new java.awt.Dimension(200, 200));
        ItemPreviewImage.setMinimumSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        previewItemPanel.add(ItemPreviewImage, gridBagConstraints);

        itemPriceText.setText("Item Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        previewItemPanel.add(itemPriceText, gridBagConstraints);

        addToCartBtn.setText("Add to Cart");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        previewItemPanel.add(addToCartBtn, gridBagConstraints);

        cancelAddToCartBtn.setText("Cancel");
        cancelAddToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddToCartBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        previewItemPanel.add(cancelAddToCartBtn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        previewItemPanel.add(itemPriceLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        previewItemPanel.add(itemNameLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 20);
        storePanel.add(previewItemPanel, gridBagConstraints);

        shoppingCartPaintPanel.setBackground(new java.awt.Color(206, 209, 213));

        shoppingCartLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/uberstockCartLogo.jpg"))); // NOI18N

        cartTextLbl.setForeground(new java.awt.Color(199, 32, 44));
        cartTextLbl.setText("Shopping Cart");

        javax.swing.GroupLayout shoppingCartPaintPanelLayout = new javax.swing.GroupLayout(shoppingCartPaintPanel);
        shoppingCartPaintPanel.setLayout(shoppingCartPaintPanelLayout);
        shoppingCartPaintPanelLayout.setHorizontalGroup(
            shoppingCartPaintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingCartPaintPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(shoppingCartLbl)
                .addGap(18, 18, 18)
                .addComponent(cartTextLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        shoppingCartPaintPanelLayout.setVerticalGroup(
            shoppingCartPaintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingCartPaintPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(shoppingCartLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shoppingCartPaintPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cartTextLbl)
                .addGap(14, 14, 14))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 20);
        storePanel.add(shoppingCartPaintPanel, gridBagConstraints);

        cartControlPanel.setLayout(new java.awt.GridBagLayout());

        checkOutCartBtn.setText("Checkout");
        checkOutCartBtn.setPreferredSize(null);
        checkOutCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutCartBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        cartControlPanel.add(checkOutCartBtn, gridBagConstraints);

        clearCartBtn.setText("Clear Cart");
        clearCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCartBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        cartControlPanel.add(clearCartBtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 18, 0, 20);
        storePanel.add(cartControlPanel, gridBagConstraints);

        categoryControlPanel.setMinimumSize(new java.awt.Dimension(150, 100));
        categoryControlPanel.setPreferredSize(new java.awt.Dimension(150, 100));
        categoryControlPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        storePanel.add(categoryControlPanel, gridBagConstraints);

        contentView.add(storePanel, "card3");

        checkoutPanel.setLayout(new java.awt.GridBagLayout());

        checkOutCartPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        checkOutCartPanel.setPreferredSize(new java.awt.Dimension(500, 600));

        checkoutCartList.setPreferredSize(new java.awt.Dimension(300, 600));
        checkoutCartList.setLayout(new java.awt.GridLayout(0, 1));
        checkOutCartPanel.setViewportView(checkoutCartList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 17, 0, 20);
        checkoutPanel.add(checkOutCartPanel, gridBagConstraints);

        papaylPanel.setLayout(new java.awt.GridBagLayout());

        firstname.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        papaylPanel.add(firstname, gridBagConstraints);

        middleinitial.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        papaylPanel.add(middleinitial, gridBagConstraints);

        lastname.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        papaylPanel.add(lastname, gridBagConstraints);

        email.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        papaylPanel.add(email, gridBagConstraints);

        jLabel2.setText("Middle Initial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        papaylPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        papaylPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        papaylPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Email Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        papaylPanel.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        checkoutPanel.add(papaylPanel, gridBagConstraints);

        confirmOrderControlPanel.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Confirm Checkout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        confirmOrderControlPanel.add(jButton1, gridBagConstraints);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        confirmOrderControlPanel.add(jButton2, gridBagConstraints);

        toggleMemberJoinBtn.setText("Become Member");
        toggleMemberJoinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleMemberJoinBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Cost $19.95 per year");

        javax.swing.GroupLayout joinMembershipPanelLayout = new javax.swing.GroupLayout(joinMembershipPanel);
        joinMembershipPanel.setLayout(joinMembershipPanelLayout);
        joinMembershipPanelLayout.setHorizontalGroup(
            joinMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
            .addGroup(joinMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(joinMembershipPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(toggleMemberJoinBtn)
                    .addGap(3, 3, 3)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        joinMembershipPanelLayout.setVerticalGroup(
            joinMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(joinMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(joinMembershipPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(joinMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(toggleMemberJoinBtn)
                        .addGroup(joinMembershipPanelLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel1)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        confirmOrderControlPanel.add(joinMembershipPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        checkoutPanel.add(confirmOrderControlPanel, gridBagConstraints);

        contentView.add(checkoutPanel, "card5");

        AdminPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        AdminPanel.add(userIDSearchField, gridBagConstraints);

        searchUserHistory.setText("See History");
        searchUserHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserHistoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        AdminPanel.add(searchUserHistory, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 800));

        UserHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(UserHistoryTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        AdminPanel.add(jScrollPane1, gridBagConstraints);

        goBackToStoreBtn.setText("Go Back");
        goBackToStoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackToStoreBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        AdminPanel.add(goBackToStoreBtn, gridBagConstraints);

        contentView.add(AdminPanel, "card6");

        getContentPane().add(contentView);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
        Login login = (Login)serviceLocator.getService("Login");
        login.setLoginUserName(UserNameField.getText());
        login.setLoginPassword(String.valueOf(PasswordField.getPassword()));
        
        //System.out.println("usernamelogin: " + login.getUserName() + " password set: " + login.getPassword());
        
        if(login.tryUserLogin())
        {
            UserNameField.setText("");
            PasswordField.setText("");
            
            incorrectLoginLabel.setVisible(false);
            
            UserNameLbl.setText("Welcome " + login.getUserName());
            cardLayout = (CardLayout)contentView.getLayout();
            cardLayout.show(contentView, "2");
            
            if(login.getAdminRights())
            {
                AdminPanelBtn.setVisible(true);
                serviceLocator.registerService("AdminPanel", new AdminPanel(UserHistoryTable, searchUserHistory, userIDSearchField));
            }
            
            repaint();
            revalidate();
            
            

        }
        else
        {
            incorrectLoginLabel.setVisible(true);
            System.err.println("Login Failed.");
        }        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void storeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBtnActionPerformed
        ShoppingCart shoppingCart = (ShoppingCart)serviceLocator.getService("ShoppingCart");
        ProductPreviewController previewController = (ProductPreviewController)serviceLocator.getService("ProductPreviewController");
        shoppingCart.reset();
        shoppingCart.clearList();
        previewController.reset();
        cartListPanel.removeAll();
        
        cardLayout = (CardLayout)contentView.getLayout();
        cardLayout.show(contentView, "1");
        UserNameLbl.setText("");
        revalidate();
    }//GEN-LAST:event_storeBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
 
        cardLayout = (CardLayout)contentView.getLayout();
        cardLayout.show(contentView, "3");
        revalidate();
    }//GEN-LAST:event_registerBtnActionPerformed

    private void registerFormCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFormCancelBtnActionPerformed
        registerFormUsernameField.setText("");
        registerConfirmPassword.setText("");
        registerSecondConfirmPassword.setText("");
        
        cardLayout = (CardLayout)contentView.getLayout();
        cardLayout.show(contentView, "1");
        revalidate();
    }//GEN-LAST:event_registerFormCancelBtnActionPerformed

    private void registerFormRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFormRegisterBtnActionPerformed
        Login login = (Login)serviceLocator.getService("Login");
        login.setLoginUserName(registerFormUsernameField.getText());
        login.setLoginPassword(String.valueOf(registerConfirmPassword.getPassword()));
        
        if(login.insertNewUser())
        {
            registerFormUsernameField.setText("");
            registerConfirmPassword.setText("");
            registerSecondConfirmPassword.setText("");
            
            login.tryUserLogin();
            UserNameLbl.setText("Welcome " + login.getUserName());
            cardLayout = (CardLayout)contentView.getLayout();
            cardLayout.show(contentView, "2");
            revalidate();
        }
        else
        {
            System.err.println("Registration Error");
        }
        
        //System.out.println("usernamelogin: " + login.getUserName() + " password set: " + login.getPassword());
    }//GEN-LAST:event_registerFormRegisterBtnActionPerformed

    
    private void cancelAddToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddToCartBtnActionPerformed
        ProductPreviewController productPreviewController = (ProductPreviewController)serviceLocator.getService("ProductPreviewController");
        ShoppingCart shoppingCart = (ShoppingCart)serviceLocator.getService("ShoppingCart");
        
        //reset product preview view
        productPreviewController.reset();
                
        //set the previously clicked product reference inside the shopping cart class to null.
        shoppingCart.setPreviewProduct(null);
        
        cartListPanel.repaint();
        
        
    }//GEN-LAST:event_cancelAddToCartBtnActionPerformed

    
    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        
        ShoppingCart shoppingCart = (ShoppingCart)serviceLocator.getService("ShoppingCart");
               
        /* Todo Handle exception thrown for parse error */
        try 
        {
            
            shoppingCart.addCartItem(Integer.parseInt(cartQuantityToAddField.getText()), cartListPanel);            

        }
        catch (InputMismatchException e) 
        {
            cartQuantityToAddField.setText("");
            //System.err.println(e.toString());
        }
        catch (NumberFormatException numberFormatException)
        {
            cartQuantityToAddField.setText("NaN");
        }     
    }//GEN-LAST:event_addToCartBtnActionPerformed

    private void clearCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCartBtnActionPerformed
        ShoppingCart shoppingCart = (ShoppingCart)serviceLocator.getService("ShoppingCart");
        ProductPreviewController productPreviewController = (ProductPreviewController)serviceLocator.getService("ProductPreviewController");
        shoppingCart.reset();
        productPreviewController.reset();
        cartListPanel.removeAll();
        repaint();
    }//GEN-LAST:event_clearCartBtnActionPerformed

    private void checkOutCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutCartBtnActionPerformed
        
        CheckoutCartController checkoutCartController = (CheckoutCartController)serviceLocator.getService("CheckoutCartController");
        
        //JPanel jPanel = new JPanel();

        
        cardLayout = (CardLayout)contentView.getLayout();
        cardLayout.show(contentView, "4");
                
        checkoutCartController.buildCheckOutList();
        revalidate();
        repaint();


    
        
    }//GEN-LAST:event_checkOutCartBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cardLayout = (CardLayout)contentView.getLayout();
        cardLayout.show(contentView, "2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void toggleMemberJoinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleMemberJoinBtnActionPerformed
        JToggleButton memberToggleButton = (JToggleButton)evt.getSource();
        CheckoutCartController checkoutCartController = (CheckoutCartController)serviceLocator.getService("CheckoutCartController");
        if(memberToggleButton.isSelected())
        {
            System.out.println("Button Toggled on");
            checkoutCartController.addMembershipFee();
            repaint();
            revalidate();
            
        }
        else
        {
            System.out.println("Button Toggled off");
            checkoutCartController.removeMembershipFee();
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_toggleMemberJoinBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CheckoutCartController checkoutCartController = (CheckoutCartController)serviceLocator.getService("CheckoutCartController");
        ShoppingCart shoppingCart = (ShoppingCart)serviceLocator.getService("ShoppingCart");
        checkoutCartController.checkOutOrder();
        checkoutCartController.reset();
        shoppingCart.clearList();
        cartListPanel.removeAll();

        repaint();
        
        cardLayout = (CardLayout)contentView.getLayout();
        cardLayout.show(contentView, "2");
        

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchUserHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserHistoryActionPerformed
        
        AdminPanel adminPanel = (AdminPanel)serviceLocator.getService("AdminPanel");
        
        adminPanel.getUserHistory();

        
        
        
    }//GEN-LAST:event_searchUserHistoryActionPerformed

    private void AdminPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPanelBtnActionPerformed
        cardLayout = (CardLayout)contentView.getLayout();
        cardLayout.show(contentView, "5");
    }//GEN-LAST:event_AdminPanelBtnActionPerformed

    private void goBackToStoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackToStoreBtnActionPerformed
        AdminPanel adminPanel = (AdminPanel)serviceLocator.getService("AdminPanel");
        adminPanel.reset();
        cardLayout = (CardLayout)contentView.getLayout();
        cardLayout.show(contentView, "2");
        
    }//GEN-LAST:event_goBackToStoreBtnActionPerformed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            loginBtn.doClick();
        }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JButton AdminPanelBtn;
    private javax.swing.JLabel ItemPreviewImage;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTable UserHistoryTable;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JButton cancelAddToCartBtn;
    private javax.swing.JPanel cartControlPanel;
    private javax.swing.JPanel cartListPanel;
    private javax.swing.JTextField cartQuantityToAddField;
    private javax.swing.JScrollPane cartScrollPanel;
    private javax.swing.JLabel cartTextLbl;
    private javax.swing.JPanel categoryControlPanel;
    private javax.swing.JButton checkOutCartBtn;
    private javax.swing.JScrollPane checkOutCartPanel;
    private javax.swing.JPanel checkoutCartList;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JButton clearCartBtn;
    private javax.swing.JPanel confirmOrderControlPanel;
    private javax.swing.JPanel contentView;
    private javax.swing.JLabel currentStockLbl;
    private javax.swing.JLabel currentStockText;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton goBackToStoreBtn;
    private javax.swing.JLabel incorrectLoginLabel;
    private javax.swing.JLabel itemNameLbl;
    private javax.swing.JLabel itemPriceLbl;
    private javax.swing.JLabel itemPriceText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel joinMembershipPanel;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField middleinitial;
    private javax.swing.JPanel paintPanel;
    private javax.swing.JPanel papaylPanel;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPanel previewItemPanel;
    private javax.swing.JPanel productBtnGrid;
    private javax.swing.JScrollPane productScrollPanel;
    private javax.swing.JLabel quantityToAddText;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registerConfirmLbl;
    private javax.swing.JPasswordField registerConfirmPassword;
    private javax.swing.JButton registerFormCancelBtn;
    private javax.swing.JButton registerFormRegisterBtn;
    private javax.swing.JTextField registerFormUsernameField;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel registerPasswordLbl;
    private javax.swing.JPasswordField registerSecondConfirmPassword;
    private javax.swing.JLabel registerUsernameLbl;
    private javax.swing.JButton searchUserHistory;
    private javax.swing.JLabel shoppingCartLbl;
    private javax.swing.JPanel shoppingCartPaintPanel;
    private javax.swing.JButton storeBtn;
    private javax.swing.JPanel storePanel;
    private javax.swing.JToggleButton toggleMemberJoinBtn;
    private javax.swing.JLabel uberStockNameLbl;
    private javax.swing.JTextField userIDSearchField;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
