/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Button;
import java.awt.CardLayout;
import java.util.Arrays;
import javax.swing.JButton;
import uberstockapp.Login;
import uberstockapp.Product;
import uberstockapp.ProductManager;
import uberstockapp.ServiceLocator;


/**
 *
 * @author Kyle
 */
public class UberStockGuiFrame extends javax.swing.JFrame {
    
    CardLayout cardLayout = null;
    ServiceLocator serviceLocator = ServiceLocator.getServiceLocatorInstance();
    /**
     * Creates new form UberStockGuiFrame
     */
    public UberStockGuiFrame() {
        initComponents();
        
        contentView.add(loginPanel, "1");
        contentView.add(storePanel, "2");

        
        ProductManager productManager = (ProductManager)serviceLocator.getService("ProductManager");
        
        
        
        for(Product product : productManager.getProductList())
        {
            
            productBtnGrid.add(new JButton(product.getName()));
            
            //System.out.println(product.getImageURI());
        }
        
        setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentView = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        passwordLbl = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        usernameLbl = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        storePanel = new javax.swing.JPanel();
        storeBtn = new javax.swing.JButton();
        productScrollPanel = new javax.swing.JScrollPane();
        productBtnGrid = new javax.swing.JPanel();
        cartScrollPanel = new javax.swing.JScrollPane();
        checkOutCartBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        paintPanel = new javax.swing.JPanel();
        clearCartBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UberStock");
        setName("uberStockFrame"); // NOI18N

        contentView.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(252, 252, 252));
        loginPanel.setLayout(new java.awt.GridBagLayout());

        loginBtn.setBackground(new java.awt.Color(206, 209, 213));
        loginBtn.setText("Login");
        loginBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        loginBtn.setMargin(new java.awt.Insets(4, 14, 4, 14));
        loginBtn.setMinimumSize(new java.awt.Dimension(78, 32));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 9, 13, 9);
        loginPanel.add(loginBtn, gridBagConstraints);

        registerBtn.setBackground(new java.awt.Color(206, 209, 213));
        registerBtn.setText("Register");
        registerBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        loginPanel.add(registerBtn, gridBagConstraints);

        passwordLbl.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        loginPanel.add(passwordLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        loginPanel.add(PasswordField, gridBagConstraints);

        usernameLbl.setText("User Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        loginPanel.add(usernameLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        loginPanel.add(UserNameField, gridBagConstraints);

        contentView.add(loginPanel, "card2");

        storePanel.setBackground(new java.awt.Color(249, 250, 251));
        storePanel.setLayout(new java.awt.GridBagLayout());

        storeBtn.setText("Goto Login Panel");
        storeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        storePanel.add(storeBtn, gridBagConstraints);

        productScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        productScrollPanel.setMinimumSize(new java.awt.Dimension(250, 400));
        productScrollPanel.setPreferredSize(new java.awt.Dimension(250, 250));

        productBtnGrid.setLayout(new java.awt.GridLayout(1, 0, 5, 5));
        productScrollPanel.setViewportView(productBtnGrid);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        storePanel.add(productScrollPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 17, 0, 20);
        storePanel.add(cartScrollPanel, gridBagConstraints);

        checkOutCartBtn.setText("Checkout");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 50);
        storePanel.add(checkOutCartBtn, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(199, 32, 44));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/uberstockLogo.png"))); // NOI18N
        jLabel1.setText("UberStock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 85;
        gridBagConstraints.insets = new java.awt.Insets(0, 17, 0, 50);
        storePanel.add(jLabel1, gridBagConstraints);

        paintPanel.setBackground(new java.awt.Color(206, 209, 213));
        paintPanel.setMinimumSize(new java.awt.Dimension(400, 60));
        paintPanel.setPreferredSize(new java.awt.Dimension(431, 60));

        javax.swing.GroupLayout paintPanelLayout = new javax.swing.GroupLayout(paintPanel);
        paintPanel.setLayout(paintPanelLayout);
        paintPanelLayout.setHorizontalGroup(
            paintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        paintPanelLayout.setVerticalGroup(
            paintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        storePanel.add(paintPanel, gridBagConstraints);

        clearCartBtn.setText("Clear Cart");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        storePanel.add(clearCartBtn, gridBagConstraints);

        contentView.add(storePanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentView, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentView, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
        Login login = (Login)serviceLocator.getService("Login");
        login.setLoginUserName(UserNameField.getText());
        login.setLoginPassword(String.valueOf(PasswordField.getPassword()));
        
        System.out.println("usernamelogin: " + login.getUserName() + " password set: " + login.getPassword());
        
        if(login.tryUserLogin())
        {
            UserNameField.setText("");
            PasswordField.setText("");
            cardLayout = (CardLayout)contentView.getLayout();
            cardLayout.show(contentView, "2");
        }
        else
        {
            System.err.println("Login Failed.");
        }
        
        //cardLayout = (CardLayout)contentView.getLayout();
        //cardLayout.show(contentView, "2");
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void storeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBtnActionPerformed
        cardLayout = (CardLayout)contentView.getLayout();
        cardLayout.show(contentView, "1");
    }//GEN-LAST:event_storeBtnActionPerformed



    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JScrollPane cartScrollPanel;
    private javax.swing.JButton checkOutCartBtn;
    private javax.swing.JButton clearCartBtn;
    private javax.swing.JPanel contentView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel paintPanel;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPanel productBtnGrid;
    private javax.swing.JScrollPane productScrollPanel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton storeBtn;
    private javax.swing.JPanel storePanel;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
